---
- name: Restart Apache
  service:
    name: "{{ apache_service }}"
    state: restarted

- name: Reload Apache
  service:
    name: "{{ apache_service }}"
    state: reloaded

- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted
